### ISSUE TITLE
eshop referencing zipkin endpoint ```zipkin.istio-system.svc.cluster.local``` 

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#135]
Based on TSB 1.6 updates, what will be the value to change it?

https://github.com/smarunich/tetrate-service-bridge-sandbox/blob/66d6d3e148bdb40887746ff1348be4bb26562b1e/modules/apps/eshop/manifests/apps/services.yaml#L60

**Comment by nacx** [comment]
No change is required. We keep the zipkin service for backwards compatibility on upgrades, but it points to OAP.
https://github.com/tetrateio/tetrate/blob/master/tsboperator/controlplane/manifests/charts/oap/templates/service-zipkin.yaml

**Comment by smarunich** [comment]
oh nice thanks for the heads up.
