### ISSUE TITLE
Consider moving this to tetrateio

### ISSUE THREAD

**Issue by nacx** [tetrateio/tetrate-service-bridge-sandbox#158]
There is already a fork of this repo in the `tetrateio` organization. However, this is the main one where development happens and it already has 7 Tetrate contributors.
We should consider deleting the fork and transferring this repo to the `tetrateio` org. It will have better visibility within the company and better encourage usage and contributions (and if I'm not wrong, by "transferring" the repo the old URLs pointing to this repo will be automatically redirected by GH).

**Comment by smarunich** [comment]
agree, I will take care about it post 1.6 release, i.e. should be done by the mid of December.

**Comment by nacx** [comment]
1.6 is out now. can we move the repo?

In the `tetrateio` org there is already a for of this. We should delete that repo first, then transfer this one.

**Comment by smarunich** [comment]
sure, will do this week

**Comment by smarunich** [comment]
completed, added CODEOWNERS
