### ISSUE TITLE
add `isolationboundary` branch for `1.6` to demo it separately

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#195]

**Comment by shamusx** [comment]
3 Revisions

Global Revision:
```
- gitops-eshop
- gitops-grpc
- gitops-opa
- gitops-direct-bookinfo
```
Dev Revision:
```
- gitops-bookinfo-dev
```

QA Revision:
```
- gitops-bookinfo-qa
```
Chose these names to be more relatable with the kbs:
https://docs.tetrate.io/service-bridge/1.6.x/en-us/setup/isolation-boundaries
