### ISSUE TITLE
[BUG] make tsb_mp generates IAM profiles and other artifacts for all supplied cluster destinations

### ISSUE THREAD

**Issue by kurktchiev** [tetrateio/tetrate-service-bridge-sandbox#219]
Currently if you supply a vars file with something like this:
```
{
    "tsb_mp": {
        "cloud": "aws",
        "cluster_id": 0
    },
    "tsb_org": "tetrate",
    "aws_k8s_regions": [
      "us-east-1",
      "us-east-2",
      "eu-west-1",
      "eu-west-2"
    ],
    "azure_k8s_regions": [
    ],
    "gcp_k8s_regions": [
    ]
}
```

and then would like to step through the process of building your environment by doing: `make tsb_mp` followed by `make tsb_cp`. The workflow is broken.

Running `make tsb_mp` creates jump boxes for every supplied cluster not just the `cluster_id` specified to be used for it. This causes a problem when you run `make tsb_cp` as IAM roles, and other profiles, specifically in AWS world, are already generated and not re-used.

Either docs need to get updated to deprecate the workflow and instead mention that you can supply only a single cluster at first and create the MP with `make tsb` and then populate subsequent clusters and run `make tsb` again. Or fix the described workflow. Alternatively, deprecate `make tsb_*` and just use the documentation approach.

**Comment by nacx** [comment]
Related to https://github.com/tetrateio/tetrate-service-bridge-sandbox/issues/73

**Comment by kurktchiev** [comment]
I believe #73 is the technical fix. Depending on wether it is the one implemented or not will dictate what a documented approach to "piece meal" building of a TSB stack would look like.

**Comment by smarunich** [comment]
This is introduced with 1.3 terraform version, i need to triage it...
