### ISSUE TITLE
Use squash/rebase by default when merging pull requests

### ISSUE THREAD

**Issue by nacx** [tetrateio/tetrate-service-bridge-sandbox#229]
Merging pull requests without squashing the commits creates a commit history that is hard to understand and reason about, as contains random WIP commits. This makes it harder to start branches from desired commits, etc.
The settings of this repo should be changed to prevent merge commits by default and use squash/rebase instead, according to the company-wide engineering guidelines we have in protocol about Git habits.

**Comment by smarunich** [comment]
can you help @nacx with setting that... I am lacking knowledge on this front...

**Comment by nacx** [comment]
I'd set this as the only merge option: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by smarunich** [comment]
ack, I don't have rights on this project. do you? do you see "settings"?

**Comment by nacx** [comment]
No, we'll need to ask #infosec then.
