### ISSUE TITLE
Update to jumpbox regexp last week breaks aws

### ISSUE THREAD

**Issue by kurktchiev** [tetrateio/tetrate-service-bridge-sandbox#236]
Just stood up an AWS env and the change from https://github.com/tetrateio/tetrate-service-bridge-sandbox/commit/d406667b515d2278d99d1b60e27e2e93e4088176, specifically the regex. Breaks AWS deploys due to the pem keys being created not having the full user supplied prefix.

Example: bk-ltlst the `bk-` will get trimmed, but when you go to deploy the CP it looks for the full prefix rather than this trimmed one, so deploys fail.

https://github.com/tetrateio/tetrate-service-bridge-sandbox/blob/fd493010a13fddb46ca9b98ac2e9e3447d768cec/modules/aws/jumpbox/main.tf#L293

**Comment by smarunich** [comment]
This is my fault, let me re-think the regex I have put in place.technically it makes '-' not supported in the name prefix...

**Comment by liyihuang** [comment]
btw I personally found the chatGPT is really good at regular expression. I have gave up to write the regular expression by myself
