### ISSUE TITLE
Argo CD Application Set instead of App of Apps

### ISSUE THREAD

**Issue by cloudcompute** [tetrateio/tetrate-service-bridge-sandbox#279]
Hi

You are using the ArgoCD [App of Apps](https://github.com/tetrateio/tetrate-service-bridge-sandbox/blob/2e0dc89a114cb6b072e10d7c3ad7ea6ecc0fbbb2/modules/addons/argocd/main.tf#L44) pattern

According to the ArgoCD documentation, this has a [limitation](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Use-Cases/) and they recommend using ApplicationSet instead.

May I ask why are you using App of Apps.. could you consider replacing it?

Thanks

**Comment by smarunich** [comment]
a fair point @cloudcompute we are tracking this under https://github.com/tetrateio/tetrate-service-bridge-sandbox/issues/220 - technically you are correct, the more context is under the issue.

Closing as dup of #220
