### ISSUE TITLE
Update to Revisioned Istio Control Plane

### ISSUE THREAD

**Issue by smarunich** [tetrateio/tetrate-service-bridge-sandbox#61]
https://docs.tetrate.io/service-bridge/1.5.x/en-us/setup/revisioned_istio#installation

**Comment by smarunich** [comment]
moved to tsb-stable flag... need to update README

**Comment by smarunich** [comment]
@shamusx fyi ^

**Comment by shamusx** [comment]
closing infavor of isolation boundary
